#!/bin/bash

type mono >/dev/null 2>&1 || { echo >&2 "Mono was not found in your PATH. Please install it with your system's package manager. Alternatively, you may use Homebrew if your system does not have traditional package management available."; exit 1; }

# REPLACE THIS WITH YOUR FARCPACK EXE
FARCPACK=/home/$USER/Games/FarcPack/FarcPack.exe

# This handles a weird mono bug.
if [[ -d "$1" ]]; then
	if [[ -d "$1.farc" ]]; then
		rm -r "$1.farc"
	fi
	touch "$1.farc"
fi

# Syntax is `farcpack <dir>` or `farcpack <.farc>`
mono "$FARCPACK" "$1"
